base_url = "https://r3dpelt.github.io"
compile_sass = false
build_search_index = true
theme = "anemone"
output_dir = "public"
default_language = "en"


[languages.en]
favicon = "favicon.ico"

[extra]
header_nav = [
{url = "/about", name_en = "/about"},
{url = "/publications", name_en = "/publications"},
{url = "/blog", name_en = "/blog"}
]



